OrdererOrgs:
- Name: Orderer
  Domain: wangchong.com
  Specs:
  - Hostname: orderer
PeerOrgs:
- Name: Org1
  Domain: org1.wangchong.com
  Template:
    Count: 2
  Users:
    Count: 1
- Name: Org2
  Domain: org2.wangchong.com
  Template:
    Count: 1
  Users:
    Count: 1